name: Docker Image Quick Check

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag knxd:latest
    - name: Inspect Docker image
      run: docker image inspect knxd:latest  
    - name: Run knxd Container
      run: |
        pwd
        docker container run knxd:latest
      timeout-minutes: 1
      continue-on-error: true
